plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id 'org.jetbrains.kotlin.jvm' version '2.4.0'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    mavenCentral()
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://maven.saps.dev/minecraft" }
    maven { url = "https://maven.isxander.dev/releases" }
    maven {
        url "https://theo.is-a.dev/maven/"
        content {
            includeGroup "dev.drtheo"
        }
    }
    maven {
        url "https://amblelabs.dev/maven"
        content {
            includeGroup "dev.amble"
            includeGroup "dev.amblelabs"
        }
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "JEI"
        url = "https://maven.blamejared.com/"
    }

    dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
        modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
        modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
        modImplementation "dev.amble:lib:${project.amblekit_version}"
        modImplementation "dev.amblelabs:ait:${project.ait_version}"
        modImplementation "net.fabricmc:fabric-language-kotlin:${project.kotlin_version}"
        modImplementation "maven.modrinth:5aaWibi9:AHxQGtuC"//trinkets
    }

    loom {
        splitEnvironmentSourceSets()
        mods {
            "doctor_m" {
                sourceSet sourceSets.main
                sourceSet sourceSets.client
            }
        }
        fabricApi {
            configureDataGeneration {
                client = true
            }
        }
    }

    processResources {
        inputs.property "version", project.version
        filesMatching("fabric.mod.json") {
            expand "version": project.version
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    jar {
        manifest {
            attributes(
                    'Specification-Title': project.name,
                    'Specification-Version': project.version,
                    'Implementation-Title': project.name,
                    'Implementation-Version': project.version,
                    'Implementation-Vendor': 'DOCTOR M',
                    'Fabric-Loader': project.loader_version,
                    'Fabric-Api': project.fabric_api_version
            )
        }
    }

    publishing {
        publications {
            create("mavenJava", MavenPublication) {
                artifactId = project.archives_base_name
                from components.java
            }
        }
    }
}