package doctor_m.client.module.dalek;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

import dev.amble.ait.client.animation.AnimationConstants;

public class ImperialDalekAnimations {
    public static final Animation START_MOVING_TRANSITION = Animation.Builder.create(0.96F)
        .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(0.0F, 0.75F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.25F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.72F, AnimationHelper.createRotationalVector(0.0F, -0.25F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, -0.75F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("eyestalk", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.12F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.36F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.56F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.84F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("plunger", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.72F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
        ))
        .addBoneAnimation("gun", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.4F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.88F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .build();

    public static final Animation MOVING = Animation.Builder.create(1.92F).looping()
        .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(0.0F, 0.75F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.25F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.72F, AnimationHelper.createRotationalVector(0.0F, -0.75F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.2F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.44F, AnimationHelper.createRotationalVector(0.0F, 0.25F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.68F, AnimationHelper.createRotationalVector(0.0F, -0.25F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("eyestalk", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.12F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.36F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.56F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.84F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.32F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.56F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.8F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.88F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("plunger", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.72F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.04F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.2F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.68F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.76F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.88F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
        ))
        .addBoneAnimation("gun", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.4F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.88F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.12F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.36F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.56F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.84F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .build();

    public static final Animation STOP_MOVING_TRANSITION = Animation.Builder.create(0.6F)
        .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.12F, AnimationHelper.createRotationalVector(0.0F, 0.75F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.36F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("eyestalk", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.12F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.36F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.56F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
        ))
        .addBoneAnimation("plunger", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
        ))
        .addBoneAnimation("gun", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.4F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
        ))
        .build();

    public static final Animation IMPERIAL_EXTERMINATE_ALT = Animation.Builder.create(2.08F)
        .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.239F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(0.0F, 1.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.4F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.12F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.24F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.36F, AnimationHelper.createRotationalVector(0.0F, -1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.64F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("body", new Transformation(Transformation.Targets.TRANSLATE,
            new Keyframe(0.0F, AnimationHelper.createTranslationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("dome", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("eyestalk", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.68F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.88F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.08F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.32F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.56F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.76F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("plunger", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.72F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.04F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.2F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.68F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.76F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.88F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
        ))
        .addBoneAnimation("gun", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.4F, AnimationHelper.createRotationalVector(-2.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.88F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.12F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.36F, AnimationHelper.createRotationalVector(-3.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.56F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.84F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("leftlight", new Transformation(Transformation.Targets.SCALE,
            new Keyframe(0.0F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(0.319F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(0.32F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(0.759F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(0.76F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(0.879F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(0.88F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(1.159F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(1.16F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(1.199F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(1.2F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(1.479F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(1.48F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(1.519F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(1.52F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(1.959F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(1.96F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP)
        ))
        .addBoneAnimation("rightlight", new Transformation(Transformation.Targets.SCALE,
                    new Keyframe(0.0F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.319F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.32F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.759F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.76F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.879F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.88F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.159F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.16F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.199F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.2F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.479F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.48F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.519F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.52F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.959F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.96F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP)
        ))
        .build();

    public static final Animation STAY_COMMAND = Animation.Builder.create(1.92F)
            .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.239F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.24F, AnimationHelper.createRotationalVector(0.0F, 1.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.12F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.24F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.36F, AnimationHelper.createRotationalVector(0.0F, -1.5F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.64F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("body", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.createTranslationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("eyestalk", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.4F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.48F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.84F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.92F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.2F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.28F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.36F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.52F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.6F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.72F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("plunger", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.24F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.72F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.04F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.2F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.68F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.76F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.88F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
            ))
            .addBoneAnimation("gun", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.28F, AnimationHelper.createRotationalVector(-2.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.36F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.64F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.72F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.88F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.08F, AnimationHelper.createRotationalVector(-3.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.44F, AnimationHelper.createRotationalVector(-3.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.68F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
            ))
            .addBoneAnimation("leftlight", new Transformation(Transformation.Targets.SCALE,
                    new Keyframe(0.0F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.199F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.2F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.439F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.44F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.599F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.6F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.839F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.84F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.959F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.96F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.199F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.2F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.319F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.32F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.679F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.68F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP)
            ))
            .addBoneAnimation("rightlight", new Transformation(Transformation.Targets.SCALE,
                    new Keyframe(0.0F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.199F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.2F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.439F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.44F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.599F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.6F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.839F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.84F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.959F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.96F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.199F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.2F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.319F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.32F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.679F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.68F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP)
            ))
            .build();

    public static final Animation DONT_MOVE_COMMAND = Animation.Builder.create(1.72F)
            .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.319F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 1.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.72F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.16F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.4F, AnimationHelper.createRotationalVector(0.0F, -1.5F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.64F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("body", new Transformation(Transformation.Targets.TRANSLATE,
                    new Keyframe(0.0F, AnimationHelper.createTranslationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
            ))
            .addBoneAnimation("eyestalk", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.4F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.48F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.84F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.92F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.2F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.36F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
            ))
            .addBoneAnimation("plunger", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.24F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.6F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.68F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.84F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.04F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.12F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.24F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.44F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.68F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
            ))
            .addBoneAnimation("gun", new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.24F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.36F, AnimationHelper.createRotationalVector(-2.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(0.56F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.72F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.16F, AnimationHelper.createRotationalVector(-3.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.24F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
                    new Keyframe(1.36F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.44F, AnimationHelper.createRotationalVector(-2.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
                    new Keyframe(1.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
            ))
            .addBoneAnimation("leftlight", new Transformation(Transformation.Targets.SCALE,
                    new Keyframe(0.0F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.319F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.32F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.599F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.6F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.719F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.72F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.919F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.92F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.119F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.12F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.519F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.52F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP)
            ))
            .addBoneAnimation("rightlight", new Transformation(Transformation.Targets.SCALE,
                    new Keyframe(0.0F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.319F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.32F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.599F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.6F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.719F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(0.72F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.919F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(0.92F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.119F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
                    new Keyframe(1.12F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.519F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
                    new Keyframe(1.52F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP)
            ))
            .build();

    public static final Animation IMPERIAL_EXTERMINATE = Animation.Builder.create(3.4F)
        .addBoneAnimation("body", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.239F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(0.0F, 1.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.4F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.12F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.24F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.36F, AnimationHelper.createRotationalVector(0.0F, -1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.64F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, 1.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.08F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.48F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.8F, AnimationHelper.createRotationalVector(0.0F, 1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(3.04F, AnimationHelper.createRotationalVector(0.0F, -1.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(3.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(3.32F, AnimationHelper.createRotationalVector(0.0F, -0.5F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("body", new Transformation(Transformation.Targets.TRANSLATE,
            new Keyframe(0.0F, AnimationHelper.createTranslationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("eyestalk", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.4F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.6F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.84F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.92F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.2F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.28F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.36F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.52F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.6F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.72F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.84F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.04F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.12F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.24F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.32F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.48F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.56F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.88F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.96F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(3.04F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(3.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(3.12F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
        ))
        .addBoneAnimation("plunger", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.08F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.72F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.8F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.04F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.2F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.44F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.68F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.76F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.88F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.92F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.16F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.24F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.36F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.64F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.72F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.84F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.88F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(3.12F, AnimationHelper.createRotationalVector(-1.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(3.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(3.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(3.36F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
        ))
        .addBoneAnimation("gun", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.28F, AnimationHelper.createRotationalVector(-2.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.36F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.48F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.64F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.72F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(0.88F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.08F, AnimationHelper.createRotationalVector(-3.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.28F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.44F, AnimationHelper.createRotationalVector(-3.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.64F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.68F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(1.84F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(1.96F, AnimationHelper.createRotationalVector(-2.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.04F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.16F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.32F, AnimationHelper.createRotationalVector(-1.5F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.56F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.76F, AnimationHelper.createRotationalVector(-3.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(2.84F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(2.96F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(3.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(3.12F, AnimationHelper.createRotationalVector(-3.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(3.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(3.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC),
            new Keyframe(3.36F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.CUBIC)
        ))
        .addBoneAnimation("leftlight", new Transformation(Transformation.Targets.SCALE,
            new Keyframe(0.0F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(0.359F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(0.36F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(0.599F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(0.6F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(0.719F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(0.72F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(1.039F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(1.04F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(1.119F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(1.12F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(1.439F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(1.44F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(1.519F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(1.52F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(1.839F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(1.84F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(1.959F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(1.96F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(2.159F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(2.16F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(2.239F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(2.24F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(2.359F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(2.36F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(2.439F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(2.44F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(2.759F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(2.76F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP),
            new Keyframe(2.879F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(2.88F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F), AnimationConstants.STEP),
            new Keyframe(3.319F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(3.32F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F), AnimationConstants.STEP)
        ))
        .addBoneAnimation("rightlight", new Transformation(Transformation.Targets.SCALE,
            new Keyframe(0.0F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(0.359F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(0.36F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(0.599F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(0.6F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(0.719F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(0.72F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(1.039F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(1.04F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(1.119F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(1.12F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(1.439F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(1.44F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(1.519F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(1.52F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(1.839F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(1.84F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(1.959F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(1.96F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(2.159F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(2.16F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(2.239F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(2.24F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(2.359F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(2.36F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(2.439F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(2.44F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(2.759F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(2.76F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(2.879F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP),
            new Keyframe(2.88F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(3.319F, AnimationHelper.createScalingVector(1.0F, 1.0F, 1.0F),AnimationConstants.STEP),
            new Keyframe(3.32F, AnimationHelper.createScalingVector(0.0F, 0.0F, 0.0F),AnimationConstants.STEP)
        ))
        .build();

    public static final Animation AIM = Animation.Builder.create(1.92F)
        .addBoneAnimation("gun", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.28F, AnimationHelper.createRotationalVector(0.0F, 1.25F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 2.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.4F, AnimationHelper.createRotationalVector(-1.25F, 2.5F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.52F, AnimationHelper.createRotationalVector(-5.0F, 2.5F, 0.0F), Transformation.Interpolations.LINEAR)
        ))
        .addBoneAnimation("pupil", new Transformation(Transformation.Targets.ROTATE,
            new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.2F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.24F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 22.5F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.32F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 45.0F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.4F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 67.5F), Transformation.Interpolations.LINEAR),
            new Keyframe(0.52F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 90.0F), Transformation.Interpolations.LINEAR)
        ))
        .build();
}